plugin: aws_ec2
regions:
  - us-east-1
  - us-west-2
# Group instances automatically by Name tag and Region
keyed_groups:
  - key: tags.Name
    prefix: instance
  - key: placement.region
    prefix: region
# Use private IP (assuming VPN/Peering exists) or public_ip_address
compose:
  ansible_host: private_ip_address